t/clang-version: better error reporting

diff --git a/t/clang-version b/t/clang-version
--- a/t/clang-version
+++ b/t/clang-version
@@ -6,4 +6,13 @@ IFS=
 # try to get the *newest* version available, unlike Debian's default
 # which is the oldest (right?)
 
-which clang-10 || which clang-9 || which clang-8 || which clang-7 || which clang-6
+die () {
+    {
+        echo "Could not find any clang compiler under clang-<versionnumber>."
+        echo "Please \`apt install clang-10\` or so."
+    } >&2
+    echo false
+    exit 1
+}
+
+which clang-10 || which clang-9 || which clang-8 || which clang-7 || which clang-6 || die
